@startuml
actor Owner
participant "License Manager API"
Owner -> "License Manager API" : Operation against Licenses
"License Manager API" -> Core : Request
Core -> "OIDC Client" : Authorize
"OIDC Client" -> Core : Authorized
Core -> "SCIM Client" : Get Licenses
"SCIM Client" -> Core : Data
Core -> Core : Run Operation
Core-> "License Manager API" : 200 OK
"License Manager API"-> Owner : 200 OK
@enduml
