@startuml
actor "End-User"
participant "PEP"
"End-User" -> "PEP" : Get Resource
"PEP" -> PDP : Check Policies associated
PDP-> "License Manager" : Check Licenses associated
"License Manager" -> "License Manager" : saved Licenses inspection
"License Manager"-> PDP : Permited
PDP-> "PEP" : Permited
"PEP" -> "End-User" : Resource
@enduml