@startuml
actor "End-User"
participant "User Profile"
"End-User" -> "User Profile" : Access User Profile
"User Profile" -> "Login-Service" : Authorize (OIDC)
"Login-Service" -> "User Profile" : Logged In
"User Profile" -> "SCIM Library" : Get User Attributes
"SCIM Library" -> "User Profile" : Data
"End-User"-> "User Profile" : Manage License
"User Profile" -> "End-User" : 200 OK
@enduml